codecov:
  require_ci_to_pass: true

comment:
  layout: "reach, diff, files"
  behavior: default
  require_changes: false

coverage:
  status:
    project:
      default:
        target: 0.8
        threshold: 0.02
    patch:
      default:
        target: 0.8
        threshold: 0.02
